# yaml
services:
  - type: web
    name: crossword-game-service
    runtime: python
    plan: free
    numInstances: 1
    repo: https://github.com/Alex-Oma/Crossword-Game-Project-Flask
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    envVars: # Env variables
      - key: API_BASE_URL
        value: https://crossword-game-project-flask.onrender.com